name: Flyio Backend Deployment

on:
  push: # pass on push events, configure this to change the trigger
  workflow_dispatch:
    inputs:
      branch:
        description: "Which branch to deploy?"
        required: false
        type: string
      environment:
        description: "What environment should we deploy on (eg. staging or production)"
        type: environment
        required: false

jobs:
  deploy-backend-flyio:
    name: Deploy Backend to Fly
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'staging' }}

    env:
      ENV: ${{ inputs.environment }}
      FLY_API_TOKEN: "${{ secrets.FLY_API_TOKEN }}"

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=$(git symbolic-ref --short HEAD)" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.extract_branch.outputs.branch || inputs.branch }}

      - name: Install Fly CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "/home/runner/.fly/bin" >> $GITHUB_PATH

      - name: Deploy to Fly
        run: flyctl deploy -t "${{ secrets.FLY_API_TOKEN }}" --local-only --build-arg DOPPLER_TOKEN=${{ secrets.DOPPLER_TOKEN }}
